### ISSUE TITLE
--known-extensions as default is too confusing

### ISSUE THREAD

**Issue by vrurg** [lizmat/App-Rak#30]
Perhaps it makes sense, but not to me. Not asking to make it _False_ by default, but having a way to change the default via the config file would be useful.

Sorry if I overlooked something in the docs.

**Comment by lizmat** [comment]
That's why releas 0.2.6 no longer has that, and instead has the new `--is-text` as default.  Which means it will search *all* files that look like they have text in them.

Regarding setting defaults, check out https://dev.to/lizmat/its-time-to-rak-part-2-18ha , specifically the "Setting up default options"

**Comment by lizmat** [comment]
FWIW, the reason I didn't select that initially, is that I feared that checking for textiness of files, would be too much of a performance drain (based on `Data::TextOrBinary`).  I've added an nqp-ified version to `path-utils` as `path-is-text`, which is 4x as fast for text files, and 6x as fast for binary files.  Which put it on par with the extension checks wrt performance.

**Comment by vrurg** [comment]
First: it looks like I haven't upgraded for too long. :)

Second: I have to find out how the documentation part about '(default)' escaped my attention!

Thanks Liz!
