### ISSUE TITLE
unexpected default extensions 

### ISSUE THREAD

**Issue by finanalyst** [lizmat/App-Rak#41]
I have lots of files with `.css` and `.scss`.
- `rak '.table' lib/plugins` ==> no result
- `rak '.table' lib/plugins --extensions=css scss` ==> lots of files
- `rak '.table' lib/plugins --extensions=* ==> no results

Suggestions
1. add group `#css` with 'css', 'scss', 'sass' (maybe others with css, eg less)
2. offer a way to allow all extensions (eg --extensions=*), or document same if it exists
3. document that rak only looks at known extensions by default.

**Comment by lizmat** [comment]
@finanalyst The reason I asked which version you were using, is that since:
````
0.2.6  2022-11-14T18:15:53+01:00
     - Bump dependency on rak to get "is-text" support
     - Add "is-text" option to indicate selecting files with text
       rather than with binary data.  Made that also the default
       rather than --known-extensions.  Can specify --/is-text to
       select files with binary data, but that only makes sense
       when --find is also specified for now.  Refuse to search
       binary files otherwise (at least for now).
````
the default for searching is *all* files that look like text files.  I'm assuming `.css` and `.scss` and `.sass` files can be considered text files.

If you're using 0.2.6 or later of App::Rak, then there's something weird going on.  If not, you will need to update :-)

**Comment by finanalyst** [comment]
@lizmat I was using rak from 0.2.3.
Issue resolved
